application:
  applicationName: foo
  deployment:
    env:
      SERVICE:
        value: "foo"
      AGENT_HOSTNAME:
        value: "alloy-ss.alloy-ss.svc.cluster.local"
      BAR_ENDPOINT:
        value: "http://bar.bar.svc.cluster.local:5000/bar"
    image:
      repository: 437023642520.dkr.ecr.us-east-2.amazonaws.com/foo
      tag: 6d5590f0a95fa73f042ce29b44a855b4a8181791
    resources:
      limits:
        memory: 64Mi
        cpu: 0.1
      requests:
        memory: 64Mi
        cpu: 0.05
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
  service:
    ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
  serviceMonitor:
    enabled: true
    additionalLabels:
      service_name: foo
    endpoints:
    - interval: 15s
      path: /metrics
      port: http
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: bar
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
      - host: foo.sandbox.lgtm.vtatarin.xyz
        paths:
        - path: /
          pathType: Prefix
