external-dns:
  provider: aws
  aws:
    region: us-east-2
    zoneType: public
  domainFilters:
    - sandbox.lgtm.vtatarin.xyz
  serviceAccount:
    name: external-dns
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::437023642520:role/eks-sandbox-external-dns
