apiVersion: v1
kind: Service
metadata:
  name: {{ template "aws-load-balancer-controller.fullname" .Subcharts.lb }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-load-balancer-controller.labels" .Subcharts.lb | nindent 4 }}
spec:
  ports:
    - port: 8080
      name: metrics-server
      targetPort: metrics-server
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" .Subcharts.lb | nindent 4 }}
